### ISSUE TITLE
Feature 1 : User can search current weather by city

### ISSUE THREAD

**Issue by semilee6557** [semilee6557/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search current weather by city
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If user enter city name, user will see list of similar names. and user can select one of them to add in the favorite list
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-27 at 10 11 33 PM](https://user-images.githubusercontent.com/61755795/135026966-64d24ded-9a2b-452d-a0b8-a3b04a165099.png)
![Screen Shot 2021-09-27 at 10 11 24 PM](https://user-images.githubusercontent.com/61755795/135026967-de40a93d-3b06-4ab6-bfea-a10d69e5d373.png)
![Screen Shot 2021-09-27 at 10 11 08 PM](https://user-images.githubusercontent.com/61755795/135026969-6beb0c58-8ba9-4532-b692-d85184bff793.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create API endpoint to search by city. 
- [ ] Create API endpoint to save a city in favorite list.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
