### ISSUE TITLE
Feature 2 : User can save a city to their favorite list

### ISSUE THREAD

**Issue by semilee6557** [semilee6557/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a city to their favorite list
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-29 at 9 18 41 PM](https://user-images.githubusercontent.com/61755795/135386553-f9e652b3-8fd5-4cf9-8d23-d0c9956cf0d4.png)
![Screen Shot 2021-09-29 at 9 18 33 PM](https://user-images.githubusercontent.com/61755795/135386562-0540d703-8fb3-4031-8bd7-8716b5319716.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create API endpoint to add city data in favorite list
- [ ] Create API endpoint to bring favorite list data
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
