### ISSUE TITLE
Feature 3 : User can remove a city from their favorites list

### ISSUE THREAD

**Issue by semilee6557** [semilee6557/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove a city from their favorites list
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-29 at 9 23 37 PM](https://user-images.githubusercontent.com/61755795/135386956-48c7a95f-545d-4352-a553-422e12c03b4a.png)
![Screen Shot 2021-09-29 at 9 23 28 PM](https://user-images.githubusercontent.com/61755795/135386960-d4492b64-e886-485e-8d8a-64dad3af333a.png)
![Screen Shot 2021-09-29 at 9 23 20 PM](https://user-images.githubusercontent.com/61755795/135386961-3c50c0fa-c591-472e-8e9f-956a85cb616e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create API endpoint to delete city data from favorite list
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
