### ISSUE TITLE
Feature 4 : User can change app between light and dark mode

### ISSUE THREAD

**Issue by semilee6557** [semilee6557/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can change app between light and dark mode
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-29 at 9 24 45 PM](https://user-images.githubusercontent.com/61755795/135387079-c828e8a3-d61d-4fa4-93dc-f4c74dd899b7.png)
![Screen Shot 2021-09-29 at 9 24 34 PM](https://user-images.githubusercontent.com/61755795/135387081-8d7a4aaa-2bf3-428b-9772-ad1ed27192a8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] add classes and css to change color between light and dark mode
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
