### ISSUE TITLE
Feature 5: User can view a list of their favorite

### ISSUE THREAD

**Issue by semilee6557** [semilee6557/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of their favorite
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-29 at 9 25 25 PM](https://user-images.githubusercontent.com/61755795/135387157-c9e10fcb-5dff-40ce-b088-ecc87c42707c.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create API endpoint for data of favorite list 
- [ ] Display favorite list in the card on home screen 
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
